### PR TITLE
update frontend

### PR DESCRIPTION
**Pull request by martinvibes**

### CODE REVIEW

**Comment by caseywescott** [comment]
Dude this looks awesome!!! If you have time would you tinker with the explore button and align the text and arrow?

**Comment by martinvibes** [comment]
yes of course i'll do that and add some cool animations #2

**Comment by martinvibes** [comment]
hey @caseywescott kindly review sir 
your site is looking good now :)
it's all the designers idea :+1:

**Comment by caseywescott** [comment]
Dude! I absolutely love the updates! This looks amazing! Thank you so so much!!

**Comment by caseywescott** [comment]
Merging!

**Pull request merged**
